services:
  giocci_relay:
    image: ghcr.io/biyooon-ex/giocci_platform/giocci_relay:0.6.0
    build:
      context: ../../
      dockerfile: ./apps/giocci_relay/Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    volumes:
      - ./config/giocci_relay.exs:/app/giocci_relay.exs:ro
      - ./config/zenoh.json5:/app/zenoh.json5:ro
    environment:
      - ZENOHD_CONNECT_ENDPOINTS
    restart: "always"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
