name: CI

env:
  OTP_VERSION: 27.1.2
  ELIXIR_VERSION: 1.17.3
  MIX_ENV: test

# based https://github.com/erlef/setup-beam

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: ${{env.OTP_VERSION}}
          elixir-version: ${{env.ELIXIR_VERSION}}

      - uses: actions/cache@v4
        id: save-deps-cache
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('**/*.lock') }}

      - name: build deps
        if: steps.save-deps-cache.outputs.cache-hit != 'true'
        run: mix do deps.get, deps.compile

  code-analysis:
    needs: build-deps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: ${{env.OTP_VERSION}}
          elixir-version: ${{env.ELIXIR_VERSION}}

      - uses: actions/cache/restore@v4
        id: restore-deps-cache
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('**/*.lock') }}
          restore-keys: deps-${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-

      - name: format
        run: mix format --check-formatted

  compile:
    needs: build-deps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          otp-version: ${{env.OTP_VERSION}}
          elixir-version: ${{env.ELIXIR_VERSION}}

      - uses: actions/cache/restore@v4
        id: restore-deps-cache
        with:
          path: |
            deps
            _build
          key: deps-${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('**/*.lock') }}
          restore-keys: deps-${{ runner.os }}-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-

      - name: compile
        run: mix compile
